"""add event_group_id to health_metrics

Revision ID: add_event_group_id_to_health_metrics
Revises: add_health_metric_edges
Create Date: 2026-05-18 18:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add_event_group_id_to_health_metrics"
down_revision = "add_health_metric_edges"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('event_group_id', sa.String(length=255), nullable=True))
    op.create_index('ix_health_metrics_user_event_group', 'health_metrics', ['user_id', 'event_group_id'], unique=False)
    # No backfill needed because nullable column defaults to NULL
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_metrics_user_event_group', table_name='health_metrics')
    op.drop_column('health_metrics', 'event_group_id')
    # ### end Alembic commands ###
